spring.application.name=Real-Time-Collaborative-Document-Editor

spring.datasource.url=jdbc:postgresql://localhost:5432/Document-Editor
spring.datasource.username=postgres
spring.datasource.password=Rohith2005rtg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

